<?php
/**
 * 请求重定向
 */

$user_class=array(
    "/favicon.ico"=>'favicion',                                                                         //favicon.ico图标
    "/Login/"=>"Login",                                                                                  //登入判断
    "/exit/"=>"exit",                                                                                     //退出调用
    "/default/"=>"test",                                                                              //默认的页面
    "/ReceiveMAC/"=>"ReceiveMAC",                                                                       //接收游戏发过了MAC
    "/changePassword/"=>"changePassword",                                                             //修改密码
    "/changePasswordGet/"=>"changePasswordGet",                                                      //修改密码提交
    "/index/"=>"index",                                                                                  // index
    "/ObjectSet/"=>"ObjectSet",                                                                         //项目管理
    "/ObjectSetGet/"=>"ObjectSetGet",                                                                  //项目管理提交
    "/UserSet/"=>"UserSet",                                                                             //增加用户
    "/UserSetGet/"=>"UserSetGet",                                                                       //增加用户处理
    "/ChangeUserSet/"=>"ChangeUserSet",                                                                //修改用户状态
    "/DeleteUserGet/"=>"DeleteUserGet",                                                                //禁用用户
    "/PageGet/"=>"PageGet",                                                                              //判断管理还是平台页面
    "/ServerSet/"=>"ServerSet",                                                                         //服务器增加
    "/ResourceServer/"=>"ResourceServer",                                                             //资源服务器
    "/ResourceServerGet/"=>"ResourceServerGet",                                                      //资源服务器增加
    "/GameServer/"=>"GameServer",                                                                      //GameServer设置
    "/GameServerGet/"=>"GameServerGet",                                                               //
    "/indexPage/"=>"indexPage",                                                                         //普通用户
    "/UserServerSelectGet/"=>"UserServerSelectGet",                                                  //指定服务器数据
    "/DayReport/"=>"DayReport",                                                                          //创建日表
    "/DayReportGet/"=>"DayReportGet",                                                                   //创建日表提交
    "/DayReportFromUserInfo/"=>"DayReportFromUserInfo",                                              //查询新用户来源
    "/HoursReport/"=>"HoursReport",                                                                     //创建时表
    "/HoursReportGet/"=>"HoursReportGet",                                                              //创建时报提交
    "/OnlineImg/"=>"OnlineImg",                                                                          //在线图标
    "/OnlineImgGet/"=>"OnlineImgGet",                                                                  //在线图标提交
    "/RealTime/"=>"RealTime",                                                                            //实时监控数据
    "/RealTimeGet/"=>"RealTimeGet",                                                                     //时间监控提交
    "/LevelCount/"=>"LevelCount",                                                                        //等级流失率
    "/LevelCountGet/"=>"LevelCountGet",                                                                //等级流失率提交
    "/LevelCountSort/"=>"LevelCountSort",                                                              //等级页面数据排序
    "/ActiveUsers/"=>"ActiveUsers",                                                                     //活跃用户
    "/PayList/"=>"PayList",                                                                               //订单查询
    "/PayListGet/"=>"PayListGet",                                                                               //订单查询
    "/PayDayReport/"=>"PayDayReport",                                                                    //充值日报表
    "/PayHoursReport/"=>"PayHoursReport",                                                               //充值时段分析
    "/PaySumAnalyse/"=>"PaySumAnalyse",                                                                 //消费总额分析
    "/ServerGet/"=>"ServerGet",                                                                          //修改服务器的范围
    "/FirstPayAnalyse/"=>"FirstPayAnalyse",                                                            //首次消费额度分析
    "/TimesPayAnalyse/"=>"TimesPayAnalyse",                                                            //单笔消费额度分析
    "/PayRanking/"=>"PayRanking",                                                                        //充值排名
    "/AllNewReport/"=>"AllNewReport",
    "/AllOnlineReport/"=>"AllOnlineReport",                                                            //所有服务器在线报表
    "/AllPayReport/"=>"AllPayReport",
    "/UserRoleList/"=>"UserRoleList",                                                                    //玩家列表
    "/UserDoingLog/"=>"UserDoingLog",                                                                    //玩家动作列表
    "/UserLoginLog/"=>"UserLoginLog",                                                                    //玩家登录
    "/UserDoingLogGet/"=>"UserDoingLogGet",                                                             //玩家动作查询
    "/UserDoingLogBlur/"=>"UserDoingLogBlur",
    "/UserLoginLogGet/"=>"UserLoginLogGet",
    "/UserRoleListGet/"=>"UserRoleListGet",                                                              //角色提交
    "/UserRoleListBlur/"=>"UserRoleListBlur",                                                            //角色进一步搜索
    "/UserOrganize/"=>"UserOrganize",                                                                     //工会列表
    "/AcerApplyList/"=>"AcerApplyList",                                                                  //元宝申请记录
    "/AcerApply/"=>"AcerApply",                                                                           //元宝申请
    "/AcerApplyGet/"=>"AcerApplyGet",                                                                     //元宝申请提交
    "/AcerApplyListGet/"=>"AcerApplyListGet",                                                           //元宝列表提交
    "/AcerApplyListBlur/"=>"AcerApplyListBlur",                                                         //申请元宝列表详细查询
    "/AcreInspect/"=>"AcreInspect",                                                                       //元宝审核
    "/AcerInspectGet/"=>"AcerInspectGet",                                                                //元宝审核提交
    "/AcerInspectBlur/"=>"AcerInspectBlur",                                                              //元宝审核细节
    "/AcreInspectControl/"=>"AcreInspectControl",                                                        //元宝审核操作
    "/AddGag/"=>"AddGag",                                                                                    //禁言
    "/AddGagGet/"=>"AddGagGet",                                                                             //禁言提交
    "/MergeGameServer/"=>"MergeGameServer",                                                               //合并服务器
    "/ChangeObjectGet/"=>"ChangeObjectGet",                                                               //合并区服时异步获取
    "/MergeGameServerGet/"=>"MergeGameServerGet",                                                        //和服提交
    "/ServerRelieveGet/"=>"ServerRelieveGet",                                                             //解除服务器合并
    "/OAllCreateReport/"=>"OAllCreateReport",                                                               //全平台创建率
    "/OAllCreateReportGet/"=>"OAllCreateReportGet",                                                        //全平台时间提交
    "/OAllOnlineReport/"=>"OAllOnlineReport",                                                               //全平台在线情况
    "/OAllPayReport/"=>"OAllPayReport",                                                                      //全平台充值
    "/GagListSet/"=>"GagListSet",                                                                            //禁言管理
    "/GagListSetGet/"=>"GagListSetGet",                                                                     //禁言表列提交
    "/GagListSetBlur/"=>"GagListSetBlur",                                                                    //禁言自动提交
    "/GagReleaseGet/"=>"GagReleaseGet",                                                                     //解除禁言
    "/AddBanNumber/"=>"AddBanNumber",                                                                        //增加账号禁止
    "/BanNumberSet/"=>"BanNumberSet",                                                                        //账号列表
    "/AddBanNumberGet/"=>"AddBanNumberGet",                                                                  //封号提交
    "/BanNumberSetBlur/"=>"BanNumberSetBlur",                                                               //封号列表失去焦点
    "/BanNumberReleaseGet/"=>"BanNumberReleaseGet",                                                        //解除封号
    "/DoingLogShow/"=>"DoingLogShow",                                                                         //操作日志
    "/DoingLogShowGet/"=>"DoingLogShowGet",                                                                  //操作日志提交
    "/NoticeAdd/"=>"NoticeAdd",                                                                                //公告发布
    "/NoticeAddPost/"=>"NoticeAddPost",                                                                       //公告提交
    "/UserRetention/"=>"UserRetention",                                                                       //用户留存率
    "/UserRetentionGet/"=>"UserRetentionGet",                                                                //用户留存率提交
    "/SendPropEmil/"=>"SendPropEmil",                                                                          //发送道具邮件
    "/SendPropEmilGet_Buffer/"=>"SendPropEmilGet_Buffer",                                                   //发送道具邮件缓存
    "/SendPropEmilGet/"=>"SendPropEmilGet",                                                                    //发送道具邮件提交
    "/ServiceSelectUserInfo/"=>"ServiceSelectUserInfo",                                                    //客户对玩家信息查询
    "/ServiceSelectUserInfoGet/"=>"ServiceSelectUserInfoGet",                                                    //客户对玩家信息查询提交
    "/ConsumeAnalysis/"=>"ConsumeAnalysis",
    "/ConsumeRankingGet/"=>"ConsumeRankingGet",
    "/SendObjectPropEmil/"=>"SendObjectPropEmil",                                                             //范围发送道具邮件
    "/SendObjectPropEmilGet/"=>"SendObjectPropEmilGet",                                                      //范围发送道具邮件提交
    "/SUserOffline/"=>"SUserOffline",                                                                           //玩家踢下线
    "/SUserOfflineGet/"=>"SUserOfflineGet",                                                                    //踢下线提交
    "/NoticeList/"=>"NoticeList",                                                                              //公告列表
    "/NoticeListGet/"=>"NoticeListGet",                                                                       //公告停止
    "/UserLoginLogChangePage/"=>"UserLoginLogChangePage",                                                  //修改显示页面
    "/SendMailList/"=>"SendMailList",                                                                          //发送邮件列表
    "/SendMail/"=>"SendMail",                                                                                    //发送邮件
    "/SUerPaySelect/"=>"SUerPaySelect",                                                                        //玩家订单号查询
    "/SUerPaySelectGet/"=>"SUerPaySelectGet",                                                                 //玩家订单号查询查询
    "/SUserControlLog/"=>"SUserControlLog",                                                                    //对玩家控制查询
    "/SUserControlLogChangePage/"=>"SUserControlLogChangePage",                                             //对玩家控制查询页面修改
    "/ShowPageGet/"=>"ShowPageGet",                                                                              //页面显示页数修改
    "/FirstPayLevel/"=>"FirstPayLevel",                                                                         //首消费等级
    "/pageIntChangePage/"=>"pageIntChangePage",
    "/ConsumeRanking/"=>"ConsumeRanking",
    "/DfromReport/"=>"DfromReport",                                                                               //渠道统计
    "/DfromReportGet/"=>"DfromReportGet",                                                                        //渠道统计提交
    "/DGoldReport/"=>"DGoldReport",                                                                               //金币统计
    "/DGoldReportGet/"=>"DGoldReportGet",                                                                         //金币统计提交
    "/ConsumeAnalysisGet/"=>"ConsumeAnalysisGet",
    "/DUserInfoReport/"=>"DUserInfoReport",                                                                       //玩家信息统计
    "/DUserInfoReportGet/"=>"DUserInfoReportGet",                                                                //玩家信息统计提交
    "/ConsumeAnalysisShowGet/"=>"ConsumeAnalysisShowGet",
    "/DUserDistribu/"=>"DUserDistribu",                                                                            //玩家分布
    "/DUserDistribuGet/"=>"DUserDistribuGet",                                                                     //玩家分布提交
    "/AllUserLeave/"=>"AllUserLeave",                                                                               //全服留存率
    "/AllUserLeaveGet/"=>"AllUserLeaveGet",                                                                        //全服留存率提交
    "/DUserDistribuStyleGet/"=>"DUserDistribuStyleGet",                                                          //
    "/downloadExlPost/"=>"downloadExlPost",                                                                        //下载数据提交
    "/downloadExl/"=>"downloadExl",                                                                                 //下载数据
    "/STalkManageSet/"=>"STalkManageSet",                                                                           //聊天系统敏感词
    "/STalkManageSetGet/"=>"STalkManageSetGet",                                                                    //聊天提交
    "/LevelCountAjax/"=>"LevelCountAjax",                                                                           //等级流失异步查询
    "/LevelCountShowList/"=>"LevelCountShowList",                                                                 //等级流失列表展现
    "/ActiveUsersGet/"=>"ActiveUsersGet",
    "/OPropEmilList/"=>"OPropEmilList",                                                                               //道具邮件列表
    "/DTaskGroup/"=>"DTaskGroup",
    "/DTaskGroupSet/"=>"DTaskGroupSet",
    "/DNewPayActive/"=>"DNewPayActive",
    "/DVIPUserActive/"=>"DVIPUserActive",
    "/OVirtualPayList/"=>"OVirtualPayList",                                                                          //需要充值
    "/OVirtualPayListGet/"=>"OVirtualPayListGet",                                                                   //需要充值
    "/DUserPayTable/"=>"DUserPayTable",                                                                              //新用户充值月充值表
    "/DUserPayTableGet/"=>"DUserPayTableGet",                                                                       //新用户充值月充值表提交
    "/OVirtualPayLog/"=>"OVirtualPayLog",                                                                            //虚假充值记录
    "/OSendPropNumberEmil/"=>"OSendPropNumberEmil",                                                                   //道具多数量邮
    "/OSendPropNumberEmilGet/"=>"OSendPropNumberEmilGet",
    "/AllServerReport/"=>"AllServerReport",
    "/AllServerReportGet/"=>"AllServerReportGet",
    "/AllUserRepeat/"=>"AllUserRepeat",                                                                               //各区用户去重
    "/PayNumberReport/"=>"PayNumberReport",                                                                           //充值次数分析
    "/PayNumberReportGet/"=>"PayNumberReportGet",                                                                   //充值次数分析提交
    "/UserGoldRanking/"=>"UserGoldRanking",                                                                           //用户持有元宝排名
    "/AllUserGoldRanking/"=>"AllUserGoldRanking",                                                                    //全服持有元宝排名
    "/SUerPropSelect/"=>"SUerPropSelect",                                                                              //玩家穿戴、仓库、背包查询
    "/SUerPropSelectGet/"=>"SUerPropSelectGet",                                                                       //玩家穿戴、仓库、背包查询提交
    "/SUerDoingSelect/"=>"SUerDoingSelect",
    "/SUerDoingSelectGet/"=>"SUerDoingSelectGet",

    "/FAllServerPay/"=>"FAllServerPay",
    "/FAllServerPayList/"=>"FAllServerPayList",
    "/FAllServerPayGet/"=>"FAllServerPayGet",
    "/FAllServerPayListGet/"=>"FAllServerPayListGet",

    "/ObjectNoticeSet/"=>"ObjectNoticeSet",                                                                           //平台公告发布
    "/ObjectNoticeSetGet/"=>"ObjectNoticeSetGet",
    "/ObjectNotice/"=>"ObjectNotice",                                                                                  //游戏端提取公告
    "/OShowGameServerSet/"=>"OShowGameServerSet",
    "/OShowGameServerGet/"=>"OShowGameServerGet",
    "/ShowGameServer/"=>"ShowGameServer",                                                                      //区服开发设置
    "/PayRankingDoaload/"=>"PayRankingDoaload",                                                                       //排名下载
    "/SendPropList/"=>"SendPropList",
    "/SendPropListPost/"=>"SendPropListPost",
    "/UserAllRoleList/"=>"UserAllRoleList",
    "/SlimitConnection/"=>"SlimitConnection",                                                                       //限制ip链接
    "/SlimitConnectionGet/"=>"SlimitConnectionGet",                                                                 //限制ip链接提交
    "/SlimitConnectionLog/"=>"SlimitConnectionLog",                                                                 //限制ip链接提交日志



    //子渠道用的
    "/FIndexFrom/"=>"FIndexFrom",                                                                                    //渠道用
    "/FIndexFromGet/"=>"FIndexFromGet",                                                                             //
    "/FAllPayReport/"=>"FAllPayReport",                                                                             //渠道用全职充值
    "/FAllPayReportGet/"=>"FAllPayReportGet",                                                                      //渠道全服提交
    "/FImportUser/"=>"FImportUser",                                                                                  //渠道导入用户
    "/FImportUserGet/"=>"FImportUserGet",                                                                           //渠道导入用户提交
    "/FPayListSelect/"=>"FPayListSelect",                                                                           //充值订单
    "/FPayListSelectGet/"=>"FPayListSelectGet",                                                                    //充值提单提交
    "/FUserRetention/"=>"FUserRetention",                                                                           //留存率
    "/FUserRetentionGet/"=>"FUserRetentionGet",                                                                    //留存率提交
    "/ConsumeAnalysisShow/"=>"ConsumeAnalysisShow",




    "/cc_s/"=>"cc_s",
    "/cc/"=>"cc",
    "/test/"=>"test"
);
?>